import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { readVocabulary, tokenize } from "../../src/lib/wordpiece.ts";
import fixture from "./fixtures/wordpiece.json" with { type: "json" };

// The subset the cases reach, so this needs neither a build nor the network.
const vocabulary = new Map(Object.entries(fixture.vocabulary));

const ids = (text: string) => tokenize(vocabulary, text).join(", ");

describe("tokenize", () => {
	// Generated by scripts/eval/fixtures.mjs from huggingface/tokenizers itself.
	it("agrees with the reference tokenizer on every case in the corpus", () => {
		for (const [text, expected] of Object.entries(fixture.cases)) {
			assert.equal(ids(text), expected, text);
		}
	});

	it("takes the longest piece in the vocabulary before a shorter one", () => {
		const file = "[PAD]\n[UNK]\ntrans\n##ient\ntransient\n";
		assert.deepEqual(tokenize(readVocabulary(file), "transient"), [4]);
	});

	it("marks every piece after the first as continuing", () => {
		const file = "[PAD]\n[UNK]\ntrans\n##ient\n";
		assert.deepEqual(tokenize(readVocabulary(file), "transient"), [2, 3]);
	});

	it("reads a token's id off its line in the vocabulary", () => {
		const file = "[PAD]\n[UNK]\nsite\n##s\n";
		assert.deepEqual(tokenize(readVocabulary(file), "Sites"), [2, 3]);
	});

	it("falls back to the unknown token, not to nothing", () => {
		const file = "[PAD]\n[UNK]\nsite\n";
		assert.deepEqual(tokenize(readVocabulary(file), "site zzz"), [2, 1]);
	});
});
